spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  rabbitmq:
    addresses: 192.168.10.100
    port: 5672
    username: guest
    password: guest

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

wx:
  appId: wx3e6b9f1c5a7ff034
  mchId: 1614433647
  mchKey: Aa111111111122222222223333333333
  notifyUrl: http://xsrnf6.natappfree.cc/pay/notify
  returnUrl: http://127.0.0.1

alipay:
  appId: 2021003103686636
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCMYyh7Y7+UMiVMpxp7dP9lOoPULDO24qdgypZ6h5aj8m0KkCAGyG3fNS7zaU8S/YjZ/vB5wBoRT1js1xPqDDp5GN93hC1AoaLxsr/4i/CiZhFxTKAG+tzyzHagQJs0q4+M/vSOsPlaG8r6ZeeZlDqTEW0pPGkQVGA3czBv82LBKQtbnPxhxpywXlEmHGVKZEM0HsGupiKghCpg9dQ8l1+ZIgQbe2g38xziKqLJ3OzHc7t5YoEN639JsBSUcV8QLBz4VOju0/0ashOFwX1hJrU5eNTEQRa1Ntn41nFlU7sHedmIhWXp5YcJFnsVZUxiGEXk0Rn6+yeeNRBn+CbePMXrAgMBAAECggEABYL7GuUOp3XUiw7gdkpgoIvMky7tFNgPNDif8c2S93rUFx8TctC5p5LB9iKDTT6Q+eYNcOo+28Eev6WuDXlPbmOwmlOhJzFxYUXgTZTI7MdPFgCpI70DobCvU5lVvpqhtypnVZbTI1uF+5C2qAvuxMlhXMYXZeG6KVMnaq3GicjQLm1AaBuNqIE5TPMmalF5UC67ffAnIHJPBFaTZJ1Yoro6iUJWG4vMs53OfeF+HCe/4S5qOgazTs7CIXMx/8/m/bsZA8QeEqbqfrCOtrh9OuVerTNXdX/dMMkEC6VfQXZFDrE4Y3QIGpEVqxIxKO536wSWWlXSL5uwI77JgHZ/GQKBgQD/+xgk4zZKWIiNcmXQgThbj7X78JBu8Lh15zXaPn2Fe0MSL5EkLq39DzcQFnqxITFXZAZora/H8OJJGMTvJgX+iv7LlKP3rwk+LBOGrhh1djfBtr5wVYvkACcUdzRFOWMzsll89I3tdqn7ZqAeuF70Kzej/0DpmuFsB0acsgMUZQKBgQCMZdk62pmyjHq/Aitzggs1Ls1LZZHdajSgNrsgxs7O3c9MUFFnxDraCWyMQ8COEO6DbmDUk3r2LVFuu7c8xgrHAfkDTFg7qwns+ETbaQLpXOn1pSN3oIGaErtrMQqTeJH4ONe6uc1yHM1iHgTueLXAnP6CufG1XS7aqKKwwHkEDwKBgEUqZ3+wFP9JpLvzaSdJgxzaW+XTPnN7f5v7+UUbFXd3ssu7JpCMPF7gOZSTPluWCGsAj+rA43o20C3ID44+y+fXTrlbVGKcXPb7mdsON3Wll7Mz2Yko1D+q+uRAwVLjCrbxPdTRj3fWVF+lfyZN0vpOox4g3j1AqCA0ZxP31XUxAoGAdI55carZvqlxnfGnMRXdSCG6vcVs+2yYlAncALIMLyFmX+yuKH94fFsmiqwUx9y2ptaT/OcTRh0JZezhisq/V8gDewF+nsq4SssyHxVnHWXNtemLMF1IOykh/zOPnC6UwIYwUwy9yuaue66AWZpNCcNMaCsGx5K8uzsVFbg0v3ECgYBsysYdni1BetnmNqGMPOf+GweHCht3rN+vVRiFLcCXcxIeUbIzlQuZBreSgAWz3ZcOnygLnrA/u/90rC+CC1usY7H+3TNcoO60w4LUHgXI0sIjN698Xj2nd6zpcnTes5CTd2iFrBeVkWuN5Vewx/7ps/pVVeHvbLvv/fe+QVKIxA==
  aliPayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAh/OrgtIeHhIiakrV1k4R0eNTMkAh/GHZeX1yRk5+gT89r0pn13lZXK/99aMgeRAmnPdlHPHFezwbo4xFx+pnnKVebd4hlkXO/ckqi0AAW4IVpxVdztSH4Hoh+/y8bXQRp2aKef7bDNKy7ZD/DILKtiDO7jtsmpDyoEL66gUWaUgGBlkmT3Z36YJ4s+G7FGTAVyZHBGbl1rO9Bras8WZEKInymXr/1y1fVwdNhSMxopZosfjKTr6PHjz4vbQ3K9LmyRAV8b2jU4tR/GeQvG0Exvwt2kx2U16dJtmIeLwV4gGO9nRAHFJypy6EM9+PL2wSlsf9cr2LnvF2qK2aIbllNQIDAQAB
  notifyUrl: http://zql-mall.natapp1.cc/pay/notify
  returnUrl: http://127.0.0.1
