spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zhao2zilong
    url: jdbc:mysql://rm-bp1j6rje3eeag30u78o.mysql.rds.aliyuncs.com:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

  redis:
    host: 127.0.0.1
    port: 6379

  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

server:
  servlet:
    session:
      timeout: 120